### PR TITLE
highlight tokens on no-pos fields by checking getQuery on matches iterator

### PR DESCRIPTION
**Pull request by romseygeek**

### CODE REVIEW

**Comment by dweiss** [comment]
Ok, agreed. This is not intrusive and makes sense. Will this also work with analyzer-manipulated term images? (I imagine it'll be a problem with Solr where queries and index use a different analyzer but it's a different discussion...). 

I'll pull it in and try to clean it up so that tests pass, etc. Stay patient with me, sigh.

**Comment by romseygeek** [comment]
> Will this also work with analyzer-manipulated term images?

It ought to.  What it *won't* work with is multi-term queries, unfortunately.  Maybe something to look at in future is extending the MatchesIterator interface to include the matching terms, which we've talked about before but haven't previously found usecases.  Or we can take automata into account as well as simple terms when building the `token` set.

**Comment by dweiss** [comment]
bq. What it won't work with is multi-term queries, unfortunately. 

Right. It's one of those things which bring me back to my argument that if the engine/ internals can't provide an authoritative answer, there shouldn't be one at all. The "full field value highlight" is the kind of answer that, while not accurate, is  also true in the sense that "we know the value of that field matched, but we don't know where exactly".

For "keyword-style" fields the strategy in your patch will work but I'm thinking whether this should be in the code or rather something configured from the outside. So that if you *know* your field contains single-terms, you can provide a strategy that narrows down the hit range. 

I'll give it a thought.

**Comment by dweiss** [comment]
I added this to the branch (with minor changes, so can't pull in directly). The changes subtle - I added field matching so that only terms from a matching field are considered and I pulled the strategies outside of the matcher itself.

**Pull request closed without merging**
